### PR TITLE
Remove assert_instr exception for AArch64 *cvt*.

### PR DESCRIPTION
**Pull request by jacobbramley**
The LLVM code generation was improved some time ago.

### CODE REVIEW

**Comment by jacobbramley** [comment]
The Armv7 failure occurs with the latest nightly, but not the version I first tested locally. I'll bisect and try to find the cause.

**Comment by jacobbramley** [comment]
`git bisect` says it started after [89bf30e73d970ba7d0a202d35c16566a27dcf527](https://github.com/rust-lang/rust/pull/112040/commits/89bf30e73d970ba7d0a202d35c16566a27dcf527). The symptom is peculiar, though, and the cause is non-obvious (to me).

**Comment by Amanieu** [comment]
I'm happy to merge this as it is. Can you open a separate issue to track the `vld2q_dup_f32` issue?

**Comment by jacobbramley** [comment]
> Can you open a separate issue to track the `vld2q_dup_f32` issue?

https://github.com/rust-lang/rust/issues/112460

**Pull request merged**
