### PR TITLE
Re-implement some AVX functions without LLVM intrinsics

### PR DESCRIPTION
**Pull request by eduardosm**

### CODE REVIEW

**Comment by bjorn3** [comment]
Do these have the same behavior for NaN (including payload preservation if applicable), Infinity, -0.0 and so on?

**Comment by eduardosm** [comment]
They produce the same assembly as the previous implementation.

**Comment by RalfJung** [comment]
> They produce the same assembly as the previous implementation.

Producing the same assembly does not mean that LLVM guarantees the same behavior for NaNs. They might get optimized in different ways.

**Comment by eduardosm** [comment]
If you are asking if there is written documentation that allows to formally prove that both versions are functionally identical, there isn't (or at least I couldn't find it), so let's speculate.

For the shuffle part, it would surprise me if it wasn't lossless (i.e., copy a bunch of bits from one place to another without caring if they represent a NaN or some weird value).

For the FP-to-FP cast, I would consider it a LLVM bug if it didn't follow IEEE semantics (unless [fast-math flags](https://llvm.org/docs/LangRef.html#fast-math-flags) were used). Since SSE/AVX is available, it would be pointless that it falled back to X87.

**Pull request merged**
