### PR TITLE
Add AVX 512f gather, scatter and compare intrinsics

### PR DESCRIPTION
**Pull request by Daniel-B-Smith**
Builds off of https://github.com/rust-lang/stdarch/pull/862 to add the scatter intrinsics.

### CODE REVIEW

**Comment by Amanieu** [comment]
You are missing these scatter intrinsics:
- _mm512_i32scatter_ps
- _mm512_mask_i32scatter_ps
- _mm512_i32scatter_epi32
- _mm512_mask_i32scatter_epi32

**Comment by Daniel-B-Smith** [comment]
Added the remaining intrinsics

**Comment by Amanieu** [comment]
Does this PR also contain the other two? If so then just close the other two and we'll use this one. It also needs a rebase due to merge conflicts.

**Comment by Daniel-B-Smith** [comment]
I closed the other two PRs since this contains them. I'm not sure what needs to be rebased as this contains the latest master already.

**Pull request merged**
