### PR TITLE
Update proc-macro2, syn, and quote to 1.0

### PR DESCRIPTION
**Pull request by taiki-e**

### CODE REVIEW

**Comment by gnzlbg** [comment]
We need to fix CI before landing this.

**Comment by taiki-e** [comment]
It seems that building documentation has also failed (related to #815). 
It probably need to specify an edition.

**Comment by lu-zero** [comment]
I guess it should be good now?

**Comment by gnzlbg** [comment]
@lu-zero do the emulated test still fail ?

**Comment by mati865** [comment]
Emulated tests hangs and is killed because of 6 hour timeout.

**Pull request merged**
