### PR TITLE
Add vqdmul* neon instructions

### PR DESCRIPTION
**Pull request by SparrowLii**
This PR does the following:
1. Add vqdmull, vqdmlal, vqdmlsl, vqdmulh neon instructions.
2. Correct the links of vqadd and vqsub to be consistent with Clang.

### CODE REVIEW

**Comment by SparrowLii** [comment]
There seems to be bugs in the llvm.aarch64.neon.*.i32 (.i64) link types, so I currently cancel the instruction to add parameters using primitive types

**Comment by Amanieu** [comment]
What is the bug? Does the same issue happen in Clang?

**Comment by SparrowLii** [comment]
Look this [CI fail](https://github.com/rust-lang/stdarch/runs/2378839348) in #1127 , `llvm.aarch64.neon.srshl.i64` went to error `LLVM ERROR: Cannot select: 0x7f88213835b0: i64 = AArch64ISD::VSHL Constant:i64<1>, Constant:i32<2>` under the target `aarch64-linux-android`. But it did not fail on other aarch64 targets. I don't know the reason for it.

**Comment by SparrowLii** [comment]
So I now avoid using primitive type suffixes in linking (for example, using .v1i64 instead of .i64), but this will cause the compiler to not be able to optimize it into the instructions we want.

**Comment by Amanieu** [comment]
I can reproduce the crash in Clang ([godbolt](https://godbolt.org/z/aebM19oqs)), I will open a bug on LLVM.

**Comment by Amanieu** [comment]
https://bugs.llvm.org/show_bug.cgi?id=50057

**Comment by Amanieu** [comment]
We can add back the missing intrinsics once the LLVM bug is fixed.

**Pull request merged**
