### PR TITLE
Replace some calls to `pointer::offset` with `add` and `sub`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
See https://github.com/rust-lang/rust/pull/100746

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
Seeing https://github.com/rust-lang/stdarch/runs/7917316301?check_suite_focus=true (doc only change) I think CI fails not because of my changes 🤔

**Comment by lu-zero** [comment]
It looks fairly strange since nobody touched ppc64le in ages. I'll try to see if the problem is in qemu by running on real hardware ...

**Review by lu-zero — COMMENTED** [review]
The change looks fine though.

**Comment by Amanieu** [comment]
CI should be fixed by #1326, can you rebase?

**Comment by WaffleLapkin** [comment]
Rebased 👍🏻

**Pull request merged**
