### PR TITLE
Migrate Azure to the rust-lang2 org

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@pietroalbini this is failing because the group variable is missing.

**Comment by pietroalbini** [comment]
Ok, created the variable group.

**Comment by gnzlbg** [comment]
Closing and re-opening to restart the build.

**Comment by bjorn3** [comment]
```
failures:
    core_arch::x86::avx2::assert__mm_broadcastq_epi64_vpbroadcastq
    core_arch::x86::sse2::assert__mm_loadh_pd_movhpd
    core_arch::x86::sse2::assert__mm_loadl_pd_movlpd
    core_arch::x86::sse2::assert__mm_loadr_pd_movapd
    core_arch::x86::sse2::assert__mm_shuffle_pd_shufpd
    core_arch::x86::sse2::assert__mm_storeh_pd_movhpd
    core_arch::x86::sse::assert__mm_loadh_pi_movhpd
    core_arch::x86::sse::assert__mm_loadl_pi_movlpd

test result: FAILED. 2009 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out
```

Got those locally too, so CI works.

**Comment by gnzlbg** [comment]
These are probably downfall from the LLVM 9 upgrade. I'll look into them and fix them here.

**Comment by gnzlbg** [comment]
@Lokathor the GameBoy Advance build job is failing due to https://github.com/rust-lang/rust/issues/62932 so I'm going to temporarily disable it. 

There are some code gen changes for i586 targets left, some appear to be regressions. cc @nikic 

I'll try to update those later and open individual issues for them.

**Comment by gnzlbg** [comment]
@pietroalbini I modified rust-central-station and highfive for this repo, but I think I might be missing something for bors.

**Comment by pietroalbini** [comment]
Was RCS redeployed?

**Comment by Lokathor** [comment]
@gnzlbg I subscribed to the other issue, but I don't have any special skills to help out on this one

**Pull request merged**
