### PR TITLE
use min_const_generics to avoid incomplete_features

### PR DESCRIPTION
**Pull request by RalfJung**
Cc @lcnr

### CODE REVIEW

**Comment by RalfJung** [comment]
Fixing the build failure would require `cfg(bootstrap)` which, as I understand it, should not be used in stdarch... how is this usually handled?
```
error: the feature `min_const_generics` has been stable since 1.51.0 and no longer requires an attribute to enable
 --> crates/core_arch/src/lib.rs:9:5
  |
9 |     min_const_generics,
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `-D stable-features` implied by `-D warnings`
```

**Comment by Amanieu** [comment]
We try to avoid `cfg(bootstrap)` here if possible, but it's fine to add it if it is really necessary.

In this particular case I think we can just wait until the `min_const_generics` stabilization hits beta so that the bootstrap compiler uses it.

**Comment by RalfJung** [comment]
Then we better hope that nobody adds non-"min" uses of const_generics in the mean time.

**Comment by pthariensflame** [comment]
> In this particular case I think we can just wait until the min_const_generics stabilization hits beta so that the bootstrap compiler uses it.

This has happened now, right?

**Comment by Amanieu** [comment]
@RalfJung Can you rebase so CI passes?

**Comment by RalfJung** [comment]
Okay, done that.

**Comment by RalfJung** [comment]
There's a "Check Style" failure in code that I did not even touch.

**Comment by Amanieu** [comment]
Just run rustfmt from the latest nightly.

**Comment by RalfJung** [comment]
When I do `cargo +nightly fmt`, there is a *huge* diff.

I think it'd be better if someone with more knowledge of this code would fix CI here first (and possibly adjust the CI setup so that PRs are not rejected for unrelated failures...).

**Comment by Amanieu** [comment]
Try rebasing now.

**Comment by Amanieu** [comment]
Since min_const_generics is stable you can just remove the feature.

**Comment by RalfJung** [comment]
Looks like CI passes now, thanks for the help. :)

**Pull request merged**
