### PR TITLE
Altivec update (again)

### PR DESCRIPTION
**Pull request by lu-zero**
- vec_cmple
- vec_cmplt
- vec_expte
- vec_floor

### CODE REVIEW

**Comment by lu-zero** [comment]
wasm and arm aren't green. One has a codegen fault while the other timedout.

**Comment by gnzlbg** [comment]
LGTM, wasm32 is failing because nightly is broken.

**Comment by lu-zero** [comment]
thank you!

**Comment by gnzlbg** [comment]
ppc64 big endian has a failure, I don't remember why, but it was in allowed failures.

**Comment by lu-zero** [comment]
ppc64 big endiang is not really supported by qemu and I'm not keen in fixing it =/

**Pull request merged**
