### PR TITLE
docs: Fix warnings and typos.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
* Fix typo in HTML tag
* Mark some things with backticks to fix warnings about unescaped square brackets.
* Spell "initialize" correctly to fix typos.

### CODE REVIEW

**Comment by Amanieu** [comment]
Ci should be fixed by #1448, can you rebase?

**Comment by waywardmonkeys** [comment]
Rebased!

**Comment by waywardmonkeys** [comment]
But now there's a new error on some thumb targets. :) :(

**Comment by Amanieu** [comment]
Should be fixed now (#1449).

**Comment by waywardmonkeys** [comment]
Rebased again.

**Pull request merged**
