### PR TITLE
Detect MOVBE

### PR DESCRIPTION
**Pull request by calebzulawski**

### CODE REVIEW

**Comment by thomcc** [comment]
Since this is insta-stable, does this need an FCP?

(Seems like it might be overkill, but worth calling out perhaps?)

**Comment by calebzulawski** [comment]
I'm not really sure how about how an FCP or the attribute works in this case.  MOVBE itself was already stabilized, detection was omitted for whatever reason.

**Comment by thomcc** [comment]
It might just be an oversight and not need FCP then. I suspect the `since` should still be the actual version, though. I think it can be the reviewer's call either way, but just felt it's worth mentioning.

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.

**Comment by Amanieu** [comment]
Note that `movbe_target_feature` is still unstable in rustc, it should probably be stabilized there as well.

**Pull request merged**
