### PR TITLE
std_detect: add avx512fp16

### PR DESCRIPTION
**Pull request by usamoi**
get cpuid number from https://cdrdv2-public.intel.com/678970/intel-avx512-fp16.pdf

### CODE REVIEW

**Comment by Amanieu** [comment]
CI should be fixed now, can you rebase?

**Comment by Amanieu** [comment]
I noticed that `avx512fp16` is missing from the list of target features in rustc. Additionally, adding a new feature will require an FCP. I think the best way forward is for you to submit a PR to add this target feature to rustc, at which point we can start an FCP on that PR which will cover both the target feature and the feature detection in stdarch.

**Comment by usamoi** [comment]
`avx512fp16` is in the list of target features in latest nightly rustc now. Is an FCP still required? @Amanieu

**Comment by Amanieu** [comment]
This is fine to merge, but we're waiting on https://github.com/rust-lang/rust/pull/121088 to fix CI-related issues.

**Pull request merged**
