### PR TITLE
Setup Azure Pipelines

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@alexcrichton this sets up azure pipelines - I didn't manage to get the window jobs to pass (wrong rust toolchain being picked), but we can enable them later.

**Comment by gnzlbg** [comment]
@alexcrichton this is blocked on setting up the access tokens to publish to github pages.

**Comment by alexcrichton** [comment]
I think the tokens are only necessary for publishing documentation, which isn't necesarily critical nowadays, so if you want to debug the other various issues I can cover that later once this lands.

**Comment by gnzlbg** [comment]
@alexcrichton @pietroalbini already set up deploying to gh-pages

**Pull request merged**
