### PR TITLE
Altivec load instructions

### PR DESCRIPTION
**Pull request by lu-zero**
- Fix vec_ld signature
- Add vec_ldl and vec_lde

### CODE REVIEW

**Comment by Amanieu** [comment]
CI is failing.

**Comment by lu-zero** [comment]
qemu is failing apparently. I tested on real hardware on both ubuntu and gentoo.

**Comment by Amanieu** [comment]
The QEMU implementation of these instructions is [here](https://github.com/qemu/qemu/blob/master/target/ppc/mem_helper.c#L435). Does this look like a bug in qemu? If so then perhaps just disable the test with a note that it is broken on QEMU, and a link to a qemu bug report.

**Comment by lu-zero** [comment]
I'll build `qemu-8.0.0` and see if it works in a more predictable way. `qemu-7.2.0` randomly fails depending on how often it is called.

**Comment by lu-zero** [comment]
Sadly it doesn't help, what's even stranger:

```
$ qemu-ppc64le -cpu power9 /home/lu_zero/stdsimd/target/release/deps/core_arch-2e063d9da5a86a3c vec_lde

running 10 tests
test core_arch::powerpc::altivec::tests::test_vec_lde_u8 ... ok
test core_arch::powerpc::altivec::tests::test_vec_lde_u16 ... FAILED
test core_arch::powerpc::altivec::tests::test_vec_lde_u32 ... FAILED
test core_arch::powerpc::altivec::sealed::assert_vec_lde_f32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u16_lvehx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u8_lvebx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i8_lvebx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i16_lvehx ... ok

failures:

---- core_arch::powerpc::altivec::tests::test_vec_lde_u16 stdout ----
thread 'core_arch::powerpc::altivec::tests::test_vec_lde_u16' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `8192`', crates/core_arch/src/powerpc/altivec.rs:2771:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- core_arch::powerpc::altivec::tests::test_vec_lde_u32 stdout ----
thread 'core_arch::powerpc::altivec::tests::test_vec_lde_u32' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `538976256`', crates/core_arch/src/powerpc/altivec.rs:2780:13


failures:
    core_arch::powerpc::altivec::tests::test_vec_lde_u16
    core_arch::powerpc::altivec::tests::test_vec_lde_u32

test result: FAILED. 8 passed; 2 failed; 0 ignored; 0 measured; 434 filtered out; finished in 0.60s
```
```
lu_zero@sol ~/stdsimd/crates/core_arch  (master)
$ qemu-ppc64le -cpu power9 /home/lu_zero/stdsimd/target/release/deps/core_arch-2e063d9da5a86a3c vec_lde test_vec_lde_u16

running 10 tests
test core_arch::powerpc::altivec::tests::test_vec_lde_u16 ... ok
test core_arch::powerpc::altivec::tests::test_vec_lde_u32 ... ok
test core_arch::powerpc::altivec::tests::test_vec_lde_u8 ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i8_lvebx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u8_lvebx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u16_lvehx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_u32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_f32_lvewx ... ok
test core_arch::powerpc::altivec::sealed::assert_vec_lde_i16_lvehx ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 434 filtered out; finished in 0.59s
```

**Comment by lu-zero** [comment]
`valgrind` seems fine though

**Comment by Amanieu** [comment]
I think you need to use the full test name for --skip.

**Pull request merged**
