### PR TITLE
Remove `has_cpuid`

### PR DESCRIPTION
**Pull request by workingjubilee**
Implements the resolution of https://github.com/rust-lang/rust/issues/60123

### CODE REVIEW

**Comment by workingjubilee** [comment]
The FCP isn't over yet but I figured I might as well while I was looking at stdarch for other reasons.

**Comment by workingjubilee** [comment]
The FCP *is* over.

**Comment by Amanieu** [comment]
We still want to avoid executing the CPUID instruction on SGX targets.

**Comment by workingjubilee** [comment]
so like that?

**Pull request merged**
