### PR TITLE
Make the wasm and wasm64 modules unstable

### PR DESCRIPTION
**Pull request by Amanieu**
Tracking issue: https://github.com/rust-lang/rust/issues/90599

### CODE REVIEW

**Comment by Amanieu** [comment]
cc @devsnek @alexcrichton

**Comment by devsnek** [comment]
seems legit

**Comment by alexcrichton** [comment]
Personally I don't think that the wasm64 module should be unstable. All of the intrinsics were designed for wasm64 (e.g. usize/pointers instead of i32/etc) and it follows well-established conventions of module-named-after-`target_arch`. The target itself is still only available via `-Zbuild-std` which gives it more time to bake on nightly.

**Comment by Amanieu** [comment]
I would like to resolve the issue of whether to have a generic `wasm` module.

**Comment by alexcrichton** [comment]
While I understand that `wasm` is "under construction", making `wasm64` nightly-only in the meantime only serves to arbitrarily make experimentation with wasm64 harder than it otherwise would be. Can `wasm64` not require a feature gate and if necessary this is revisited before providing a rustup-installable-component?

**Comment by Amanieu** [comment]
As a general rule we don't add any stable APIs to the standard library without going through an FCP first. I personally don't think adding `wasm64` is too controversial since we already have `wasm32` stable. However I think the common `wasm` module may be more controversial. This should be discussed in the tracking issue.

**Pull request merged**
