### PR TITLE
Add vcvtq_u32_f32 and vcvtq_s32_f32

### PR DESCRIPTION
**Pull request by jrmuizel**
These intrinsics are implemented differently for aarch64 and arm
in clang. i.e. aarch64 uses the llvm.aarch64.neon.fcvtzs.v4i32.v4f32
intrinsic. However, there didn't seem to be any advantage to using
that intrinsic instead of just sharing code.

### CODE REVIEW

**Comment by Amanieu** [comment]
Can you add tests for out-of-range values? For example passing a negative value to the unsigned conversion should produce a result of 0.

**Comment by jrmuizel** [comment]
It looks like the out of range values will throw a floating point exception: https://developer.arm.com/docs/ddi0596/h/shared-pseudocode-functions/shared-functionsfloat-pseudocode#impl-shared.FPToFixed.5

**Comment by Amanieu** [comment]
That just sets an exception bit in the FP status register and returns a NaN. I'm more worried about LLVM optimizing it to `undef` and returning an arbitrary value.

**Comment by jrmuizel** [comment]
It does seem like there's some badness going on with llvm converting to undef. This shows the difference between the aarch64 and ARM approaches:
https://gcc.godbolt.org/z/5Ws1P8

It feels like the ARM behaviour is not really what you'd when using this intrinsic.

**Comment by Amanieu** [comment]
I checked the behavior with GCC and with the ACLE spec and it seems that the AArch64 behavior is the  correct one. It seems that this is a bug in Clang.

I don't think LLVM currently exposes an intrinsic for this on ARM, but you should definitely open a bug report for Clang on https://bugs.llvm.org/.

In the meantime for this PR you can just keep Clang's behavior but with a clear comment explaining that the behavior isn't 100% correct.

**Comment by Amanieu** [comment]
Can you report the Clang bug on bugs.llvm.org and add a link to the bug report in a comment?

**Comment by jrmuizel** [comment]
It looks like CI is broken because of a missing apple nightly

**Comment by Amanieu** [comment]
It's being worked on, should be fixed for tomorrow's nightlies.

**Comment by Amanieu** [comment]
CI is now fixed but there are errors.

**Comment by jrmuizel** [comment]
https://bugs.llvm.org/show_bug.cgi?id=47510

**Pull request merged**
